# Setup
title     : PIEA
tagline   : The MiNET plugins development organization.
baseurl   : ""
paginate  : 3

# About/contact
author:
  name          : PIEA
  url           : https://github.com/PIEA
  description   : The MiNET plugins development organization.

# Gems
gems:
  - jekyll-paginate

# Others
markdown: kramdown